/* Generated By:JJTree: Do not edit this line. ASTCommitStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.berkeley.cs186.database.cli.parser;

public
class ASTCommitStatement extends SimpleNode {
  public ASTCommitStatement(int id) {
    super(id);
  }

  public ASTCommitStatement(MoocParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public void jjtAccept(MoocParserVisitor visitor, Object data) {
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dce614a0cb80e248b2ece1ffcce2b0be (do not edit this line) */
