/* Generated By:JJTree: Do not edit this line. ASTCreateTableStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.berkeley.cs186.database.cli.parser;

public
class ASTCreateTableStatement extends SimpleNode {
  public ASTCreateTableStatement(int id) {
    super(id);
  }

  public ASTCreateTableStatement(MoocParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public void jjtAccept(MoocParserVisitor visitor, Object data) {
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7ad1933043411c40a9f1cf810153b7b8 (do not edit this line) */
